import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import backgroundImage from "~/assets/background.jpeg";
import Link from "next/link";
import Image from "next/image";

import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Burn Search</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col">
        <nav className="flex w-full flex-1 border-2 border-red-500">test</nav>
        <section
          className="relative min-h-[200px] w-full flex-[7] border-2 border-red-500"
          id="Hero"
        >
          <div className="absolute -z-10 h-full w-full">
            <Image
              alt="Hero background image"
              src={backgroundImage}
              layout="fill"
              objectFit="cover"
            />
          </div>
          <div title="Hero Body" className="flex flex-1 justify-center py-5">
            <h1 className="text-6xl font-bold uppercase text-white">
              Discover your camp
            </h1>
          </div>
        </section>
        <section
          className="flex min-h-[300px] w-full flex-[7] border-2 border-red-500"
          id="Browser"
        >
          div
        </section>
      </main>
    </>
  );
}
